version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: wanted-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wanted
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped